### ISSUE TITLE
Typo in the README?

### ISSUE THREAD

**Issue by myungjoo** [leemgs/tinyros2#1]
> TinyROS2 is a project started by Geunsik Lim in 2017 to reduce the size of the Linux kernel, in both memory usage and binary filesize.

Isn't it:

```
 TinyROS2 is a project started by Geunsik Lim in 2017 to reduce the size of the ROS2.
```
(Linux kernel,... --> ROS2)

**Comment by leemgs** [comment]
Fixed. Thanks.

**Comment by myungjoo** [comment]
Verified. Thanks!
